### ISSUE TITLE
remove dependency on config.gem

### ISSUE THREAD

**Issue by ichylinux** [fuminori-ido/edgarj#28]
config.gem is used to change some settings based on environment such as Rails.env.
config.gem v1.x.x uses OpenStruct#new_ostruct_member which is removed by Ruby-2.7.

fix for the removal of OpenStruct#new_ostruct_member comes on config.gem v2 but it requires majar version update.

**Comment by fuminori-ido** [comment]
Thank you for your PR.  I've merged these!
